import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from './components/frontpage/Footer'
import Heading from './components/frontpage/Heading'
import InfoEnd from './components/frontpage/InfoEnd'
import InfoMid from './components/frontpage/InfoMid'
import InfoStart from './components/frontpage/InfoStart'
import Navbar from './components/frontpage/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Seesies | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Heading />
      <InfoStart />
      <InfoMid />
      <InfoEnd />
      <Footer />
    </div>
  )
}
